drop table Cls cascade constraints;
drop table DeletedObjects cascade constraints;
drop sequence SSpecialization;
drop table Specialization cascade constraints;
drop table Association cascade constraints;
drop table Association3 cascade constraints;
drop sequence SCrtMObjctCMD;
drop table CrtMObjctCMD cascade constraints;
drop sequence SCrtUntTpCMD;
drop table CrtUntTpCMD cascade constraints;
drop sequence SCrtAspctCMD;
drop table CrtAspctCMD cascade constraints;
drop sequence SCrtUntCMD;
drop table CrtUntCMD cascade constraints;
drop sequence SAbsOprtn;
drop table AbsOprtn cascade constraints;
drop sequence SAddDfltUntCMD;
drop table AddDfltUntCMD cascade constraints;
drop sequence SRmvAssFrmHrCMD;
drop table RmvAssFrmHrCMD cascade constraints;
drop sequence SSrvr;
drop table Srvr cascade constraints;
drop sequence SRmvLnkCMD;
drop table RmvLnkCMD cascade constraints;
drop sequence SFrmlPrmtr;
drop table FrmlPrmtr cascade constraints;
drop sequence SCrtHrrchCMD;
drop table CrtHrrchCMD cascade constraints;
drop sequence SOprtnMngr;
drop table OprtnMngr cascade constraints;
drop sequence SQntfObjct;
drop table QntfObjct cascade constraints;
drop sequence SCrtMsrmntTpCMD;
drop table CrtMsrmntTpCMD cascade constraints;
drop sequence SMQntObjctTp;
drop table MQntObjctTp cascade constraints;
drop sequence SCmmndCrdntr;
drop table CmmndCrdntr cascade constraints;
drop sequence SAccntTpMngr;
drop table AccntTpMngr cascade constraints;
drop sequence SMObjct;
drop table MObjct cascade constraints;
drop sequence SCrtQnttCMD;
drop table CrtQnttCMD cascade constraints;
drop sequence SInstncObjct;
drop table InstncObjct cascade constraints;
drop sequence SRmvFpCMD;
drop table RmvFpCMD cascade constraints;
drop sequence SMBln;
drop table MBln cascade constraints;
drop sequence SFnctn;
drop table Fnctn cascade constraints;
drop sequence SAspctMngr;
drop table AspctMngr cascade constraints;
drop sequence SRmvOprtnCMD;
drop table RmvOprtnCMD cascade constraints;
drop sequence SCrtCnstntCMD;
drop table CrtCnstntCMD cascade constraints;
drop sequence SMAspct;
drop table MAspct cascade constraints;
drop sequence SAccntMngr;
drop table AccntMngr cascade constraints;
drop sequence SCrtMssgCMD;
drop table CrtMssgCMD cascade constraints;
drop sequence SCrtAccntTpCMD;
drop table CrtAccntTpCMD cascade constraints;
drop sequence SCnvrsnMngr;
drop table CnvrsnMngr cascade constraints;
drop sequence SQnttMngr;
drop table QnttMngr cascade constraints;
drop sequence SAbsUntTp;
drop table AbsUntTp cascade constraints;
drop sequence SCrtPrdctTpCMD;
drop table CrtPrdctTpCMD cascade constraints;
drop sequence SCrtSttcOpCMD;
drop table CrtSttcOpCMD cascade constraints;
drop sequence SAssctnMngr;
drop table AssctnMngr cascade constraints;
drop sequence SCrtAccntCMD;
drop table CrtAccntCMD cascade constraints;
drop sequence SCrtCnvrsnCMD;
drop table CrtCnvrsnCMD cascade constraints;
drop sequence SCrtAtmcSbTpCMD;
drop table CrtAtmcSbTpCMD cascade constraints;
drop sequence SAbsQntt;
drop table AbsQntt cascade constraints;
drop sequence SCrtVdOprtnCMD;
drop table CrtVdOprtnCMD cascade constraints;
drop sequence SCrtLnkCMD;
drop table CrtLnkCMD cascade constraints;
drop sequence SCrtCmpUntCMD;
drop table CrtCmpUntCMD cascade constraints;
drop sequence SCmmnDt;
drop table CmmnDt cascade constraints;
drop sequence SCrtCmpUntTpCMD;
drop table CrtCmpUntTpCMD cascade constraints;
drop sequence SRmvAssctnCMD;
drop table RmvAssctnCMD cascade constraints;
drop sequence SHrrch;
drop table Hrrch cascade constraints;
drop sequence SAddFpCMD;
drop table AddFpCMD cascade constraints;
drop sequence SCrtSttcMssgCMD;
drop table CrtSttcMssgCMD cascade constraints;
drop sequence STpMngr;
drop table TpMngr cascade constraints;
drop sequence SMssgMngr;
drop table MssgMngr cascade constraints;
drop sequence SUntTpMngr;
drop table UntTpMngr cascade constraints;
drop sequence SMTp;
drop table MTp cascade constraints;
drop sequence SCrtVdMssgCMD;
drop table CrtVdMssgCMD cascade constraints;
drop sequence SAbsUnt;
drop table AbsUnt cascade constraints;
drop sequence SAddAssctnCMD;
drop table AddAssctnCMD cascade constraints;
drop sequence SCrtCnstCMD;
drop table CrtCnstCMD cascade constraints;
drop sequence SFrctnMngr;
drop table FrctnMngr cascade constraints;
drop sequence SCrtOprtnCMD;
drop table CrtOprtnCMD cascade constraints;
drop sequence SCnvrsn;
drop table Cnvrsn cascade constraints;
drop sequence SRfrnc;
drop table Rfrnc cascade constraints;
drop sequence SFnshMdlngCMD;
drop table FnshMdlngCMD cascade constraints;
drop sequence SRfrncTp;
drop table RfrncTp cascade constraints;
drop sequence SMsrmntTpMng;
drop table MsrmntTpMng cascade constraints;
drop sequence SLnkMngr;
drop table LnkMngr cascade constraints;
drop sequence SCrtAssctnCMD;
drop table CrtAssctnCMD cascade constraints;
drop sequence SMssgOrLnk;
drop table MssgOrLnk cascade constraints;
drop sequence SCrtAtmcRtTpCMD;
drop table CrtAtmcRtTpCMD cascade constraints;
drop sequence SCmmndExctr;
drop table CmmndExctr cascade constraints;
drop sequence SAddRfrncTpCMD;
drop table AddRfrncTpCMD cascade constraints;
drop sequence SActlPrmtr;
drop table ActlPrmtr cascade constraints;
drop sequence SCrtSmTpCMD;
drop table CrtSmTpCMD cascade constraints;
drop sequence SRmvFpFrmOpCMD;
drop table RmvFpFrmOpCMD cascade constraints;
drop sequence SRmvMssgCMD;
drop table RmvMssgCMD cascade constraints;
drop sequence SObjctMngr;
drop table ObjctMngr cascade constraints;
drop sequence SCrtFpCMD;
drop table CrtFpCMD cascade constraints;
drop sequence SCrtMObjctCMDTps;
drop table CrtMObjctCMDTps cascade constraints;
drop sequence SMCmplxTpCntndTps;
drop table MCmplxTpCntndTps cascade constraints;
drop sequence SAbsOprtnPrmtrs;
drop table AbsOprtnPrmtrs cascade constraints;
drop sequence SCmpndQnttPrts;
drop table CmpndQnttPrts cascade constraints;
drop sequence SCmpUntTpRfs;
drop table CmpUntTpRfs cascade constraints;
drop sequence SAssctnHrrchs;
drop table AssctnHrrchs cascade constraints;
drop sequence SOprtnMngrOprtns;
drop table OprtnMngrOprtns cascade constraints;
drop sequence SOprtnMngrFrmlPrmtrs;
drop table OprtnMngrFrmlPrmtrs cascade constraints;
drop sequence SCmmndCrdntrExctr;
drop table CmmndCrdntrExctr cascade constraints;
drop sequence SAccntTpMngrAccntTps;
drop table AccntTpMngrAccntTps cascade constraints;
drop sequence SMssgActlPrmtrs;
drop table MssgActlPrmtrs cascade constraints;
drop sequence SAspctMngrAspcts;
drop table AspctMngrAspcts cascade constraints;
drop sequence SAccntMngrAccnts;
drop table AccntMngrAccnts cascade constraints;
drop sequence SCmpUntRfs;
drop table CmpUntRfs cascade constraints;
drop sequence SCrtMssgCMDAp;
drop table CrtMssgCMDAp cascade constraints;
drop sequence SCnvrsnMngrCnvrsns;
drop table CnvrsnMngrCnvrsns cascade constraints;
drop sequence SQnttMngrQntts;
drop table QnttMngrQntts cascade constraints;
drop sequence SCrtPrdctTpCMDFctrs;
drop table CrtPrdctTpCMDFctrs cascade constraints;
drop sequence SCrtSttcOpCMDFp;
drop table CrtSttcOpCMDFp cascade constraints;
drop sequence SAssctnMngrAssctns;
drop table AssctnMngrAssctns cascade constraints;
drop sequence SAssctnMngrHrrchs;
drop table AssctnMngrHrrchs cascade constraints;
drop sequence SCrtVdOprtnCMDFp;
drop table CrtVdOprtnCMDFp cascade constraints;
drop sequence SMAccntTpSbAccntTps;
drop table MAccntTpSbAccntTps cascade constraints;
drop sequence SCrtSttcMssgCMDAp;
drop table CrtSttcMssgCMDAp cascade constraints;
drop sequence STpMngrTps;
drop table TpMngrTps cascade constraints;
drop sequence SMssgMngrMssgs;
drop table MssgMngrMssgs cascade constraints;
drop sequence SUntTpMngrUntTps;
drop table UntTpMngrUntTps cascade constraints;
drop sequence SUntTpMngrUnts;
drop table UntTpMngrUnts cascade constraints;
drop sequence SCrtVdMssgCMDAp;
drop table CrtVdMssgCMDAp cascade constraints;
drop sequence SCrtOprtnCMDFp;
drop table CrtOprtnCMDFp cascade constraints;
drop sequence SAccntSbAccnts;
drop table AccntSbAccnts cascade constraints;
drop sequence SAccntEntrs;
drop table AccntEntrs cascade constraints;
drop sequence SMsrmntTpMngMsrmntTps;
drop table MsrmntTpMngMsrmntTps cascade constraints;
drop sequence SLnkMngrLnks;
drop table LnkMngrLnks cascade constraints;
drop sequence SCmmndExctrCommands;
drop table CmmndExctrCommands cascade constraints;
drop sequence SCrtSmTpCMDAddnds;
drop table CrtSmTpCMDAddnds cascade constraints;
drop sequence SObjctMngrObjcts;
drop table ObjctMngrObjcts cascade constraints;
