drop table Cls cascade constraints;
drop table DeletedObjects cascade constraints;
drop sequence SSpecialization;
drop table Specialization cascade constraints;
drop table Association cascade constraints;
drop table Association3 cascade constraints;
drop sequence STpMngr;
drop table TpMngr cascade constraints;
drop sequence SCmmndExctr;
drop table CmmndExctr cascade constraints;
drop sequence SAspctMngr;
drop table AspctMngr cascade constraints;
drop sequence SSrvr;
drop table Srvr cascade constraints;
drop sequence SNmdEntt;
drop table NmdEntt cascade constraints;
drop sequence SCrtAspctCMD;
drop table CrtAspctCMD cascade constraints;
drop sequence SCmmndCrdntr;
drop table CmmndCrdntr cascade constraints;
drop sequence SCmmnDt;
drop table CmmnDt cascade constraints;
drop sequence SAbstrctMtTp;
drop table AbstrctMtTp cascade constraints;
drop sequence SCrtTpCMD;
drop table CrtTpCMD cascade constraints;
drop sequence STpMngrAllTps;
drop table TpMngrAllTps cascade constraints;
drop sequence SCmmndExctrCommands;
drop table CmmndExctrCommands cascade constraints;
drop sequence SAspctMngrAspcts;
drop table AspctMngrAspcts cascade constraints;
drop sequence SMtAssctnHrrchs;
drop table MtAssctnHrrchs cascade constraints;
drop sequence SCmmndCrdntrExctr;
drop table CmmndCrdntrExctr cascade constraints;
drop sequence SCmpsdMtTpCmpnnts;
drop table CmpsdMtTpCmpnnts cascade constraints;
drop sequence SMtTpSbtps;
drop table MtTpSbtps cascade constraints;
