drop table Cls cascade constraints;
drop table DeletedObjects cascade constraints;
drop sequence SSpecialization;
drop table Specialization cascade constraints;
drop table Association cascade constraints;
drop table Association3 cascade constraints;
drop sequence SCnvrsnMngr;
drop table CnvrsnMngr cascade constraints;
drop sequence SQnttMngr;
drop table QnttMngr cascade constraints;
drop sequence SAbsUntTp;
drop table AbsUntTp cascade constraints;
drop sequence SAssctnMngr;
drop table AssctnMngr cascade constraints;
drop sequence SCrtUntTpCMD;
drop table CrtUntTpCMD cascade constraints;
drop sequence SMCmplxTp;
drop table MCmplxTp cascade constraints;
drop sequence SCrtCnvrsnCMD;
drop table CrtCnvrsnCMD cascade constraints;
drop sequence SAbsQntt;
drop table AbsQntt cascade constraints;
drop sequence SCrtAspctCMD;
drop table CrtAspctCMD cascade constraints;
drop sequence SMAHrrch;
drop table MAHrrch cascade constraints;
drop sequence SCrtUntCMD;
drop table CrtUntCMD cascade constraints;
drop sequence SCrtCmpUntCMD;
drop table CrtCmpUntCMD cascade constraints;
drop sequence SCmmnDt;
drop table CmmnDt cascade constraints;
drop sequence SCrtCmpUntTpCMD;
drop table CrtCmpUntTpCMD cascade constraints;
drop sequence STpMngr;
drop table TpMngr cascade constraints;
drop sequence SUntTpMngr;
drop table UntTpMngr cascade constraints;
drop sequence SAddDfltUntCMD;
drop table AddDfltUntCMD cascade constraints;
drop sequence SAbsUnt;
drop table AbsUnt cascade constraints;
drop sequence SSrvr;
drop table Srvr cascade constraints;
drop sequence SMAtmcTp;
drop table MAtmcTp cascade constraints;
drop sequence SCrtAtmcTpCMD;
drop table CrtAtmcTpCMD cascade constraints;
drop sequence SFrctnMngr;
drop table FrctnMngr cascade constraints;
drop sequence SCnvrsn;
drop table Cnvrsn cascade constraints;
drop sequence SRfrnc;
drop table Rfrnc cascade constraints;
drop sequence SCrtSbTpCMD;
drop table CrtSbTpCMD cascade constraints;
drop sequence SFnshMdlngCMD;
drop table FnshMdlngCMD cascade constraints;
drop sequence SRfrncTp;
drop table RfrncTp cascade constraints;
drop sequence SCrtHrrchCMD;
drop table CrtHrrchCMD cascade constraints;
drop sequence SCmmndCrdntr;
drop table CmmndCrdntr cascade constraints;
drop sequence SMAssctn;
drop table MAssctn cascade constraints;
drop sequence SCrtQnttCMD;
drop table CrtQnttCMD cascade constraints;
drop sequence SCrtAssctnCMD;
drop table CrtAssctnCMD cascade constraints;
drop sequence SMBln;
drop table MBln cascade constraints;
drop sequence SCmmndExctr;
drop table CmmndExctr cascade constraints;
drop sequence SAddRfrncTpCMD;
drop table AddRfrncTpCMD cascade constraints;
drop sequence SFnctn;
drop table Fnctn cascade constraints;
drop sequence SAspctMngr;
drop table AspctMngr cascade constraints;
drop sequence SAddTHrrchCMD;
drop table AddTHrrchCMD cascade constraints;
drop sequence SAddSbTpCMD;
drop table AddSbTpCMD cascade constraints;
drop sequence SMAspct;
drop table MAspct cascade constraints;
drop sequence SCnvrsnMngrCnvrsns;
drop table CnvrsnMngrCnvrsns cascade constraints;
drop sequence SQnttMngrQntts;
drop table QnttMngrQntts cascade constraints;
drop sequence SAssctnMngrAssctns;
drop table AssctnMngrAssctns cascade constraints;
drop sequence SAssctnMngrHrrchs;
drop table AssctnMngrHrrchs cascade constraints;
drop sequence SMCmplxTpCntndTps;
drop table MCmplxTpCntndTps cascade constraints;
drop sequence STpMngrAtmcTps;
drop table TpMngrAtmcTps cascade constraints;
drop sequence STpMngrPrdctTps;
drop table TpMngrPrdctTps cascade constraints;
drop sequence STpMngrSmTps;
drop table TpMngrSmTps cascade constraints;
drop sequence SUntTpMngrUntTps;
drop table UntTpMngrUntTps cascade constraints;
drop sequence SUntTpMngrUnts;
drop table UntTpMngrUnts cascade constraints;
drop sequence SCmpndQnttPrts;
drop table CmpndQnttPrts cascade constraints;
drop sequence SCmpUntTpRfs;
drop table CmpUntTpRfs cascade constraints;
drop sequence SCmmndCrdntrExctr;
drop table CmmndCrdntrExctr cascade constraints;
drop sequence SMAssctnHrrchs;
drop table MAssctnHrrchs cascade constraints;
drop sequence SCmmndExctrCommands;
drop table CmmndExctrCommands cascade constraints;
drop sequence SAspctMngrAspcts;
drop table AspctMngrAspcts cascade constraints;
drop sequence SCmpUntRfs;
drop table CmpUntRfs cascade constraints;
