drop table Cls cascade constraints;
drop table DeletedObjects cascade constraints;
drop sequence SSpecialization;
drop table Specialization cascade constraints;
drop table Association cascade constraints;
drop table Association3 cascade constraints;
drop sequence SMEnm;
drop table MEnm cascade constraints;
drop sequence SAbsObj;
drop table AbsObj cascade constraints;
drop sequence SCnvrtTDfltCMD;
drop table CnvrtTDfltCMD cascade constraints;
drop sequence SCrtEnmCMD;
drop table CrtEnmCMD cascade constraints;
drop sequence SCrtMObjctCMD;
drop table CrtMObjctCMD cascade constraints;
drop sequence SAddTpCMD;
drop table AddTpCMD cascade constraints;
drop sequence SAssgnTpCMD;
drop table AssgnTpCMD cascade constraints;
drop sequence SFtchCUCMD;
drop table FtchCUCMD cascade constraints;
drop sequence SMnStrtg;
drop table MnStrtg cascade constraints;
drop sequence SCrtUntTpCMD;
drop table CrtUntTpCMD cascade constraints;
drop sequence SRmvHrrchCMD;
drop table RmvHrrchCMD cascade constraints;
drop sequence SCrtAspctCMD;
drop table CrtAspctCMD cascade constraints;
drop sequence SCrtUntCMD;
drop table CrtUntCMD cascade constraints;
drop sequence SNSInst;
drop table NSInst cascade constraints;
drop sequence SCrTpDisjCMD;
drop table CrTpDisjCMD cascade constraints;
drop sequence SRmvTpCMD;
drop table RmvTpCMD cascade constraints;
drop sequence SAbsOprtn;
drop table AbsOprtn cascade constraints;
drop sequence SRmvAssFrmHrCMD;
drop table RmvAssFrmHrCMD cascade constraints;
drop sequence SStCnvrsnCMD;
drop table StCnvrsnCMD cascade constraints;
drop sequence SSrvr;
drop table Srvr cascade constraints;
drop sequence SNmSchm;
drop table NmSchm cascade constraints;
drop sequence SRnmAspctCMD;
drop table RnmAspctCMD cascade constraints;
drop sequence SCrTpConjCMD;
drop table CrTpConjCMD cascade constraints;
drop sequence SAssgnNmCMD;
drop table AssgnNmCMD cascade constraints;
drop sequence SChngUNmCMD;
drop table ChngUNmCMD cascade constraints;
drop sequence SAggrgtCMD;
drop table AggrgtCMD cascade constraints;
drop sequence SAddSbAccTypCMD;
drop table AddSbAccTypCMD cascade constraints;
drop sequence SRmvLnkCMD;
drop table RmvLnkCMD cascade constraints;
drop sequence SMObsrvtnTp;
drop table MObsrvtnTp cascade constraints;
drop sequence SFrmlPrmtr;
drop table FrmlPrmtr cascade constraints;
drop sequence SCrtHrrchCMD;
drop table CrtHrrchCMD cascade constraints;
drop sequence SOprtnMngr;
drop table OprtnMngr cascade constraints;
drop sequence SQntfObjct;
drop table QntfObjct cascade constraints;
drop sequence SMlCMD;
drop table MlCMD cascade constraints;
drop sequence SCrtMsrmntTpCMD;
drop table CrtMsrmntTpCMD cascade constraints;
drop sequence SMQntObjctTp;
drop table MQntObjctTp cascade constraints;
drop sequence SCmmndCrdntr;
drop table CmmndCrdntr cascade constraints;
drop sequence SAccntTpMngr;
drop table AccntTpMngr cascade constraints;
drop sequence SMObsrvtn;
drop table MObsrvtn cascade constraints;
drop sequence SMMdlItm;
drop table MMdlItm cascade constraints;
drop sequence SCrtQnttCMD;
drop table CrtQnttCMD cascade constraints;
drop sequence SRmvFpCMD;
drop table RmvFpCMD cascade constraints;
drop sequence SGtExstngCUTCMD;
drop table GtExstngCUTCMD cascade constraints;
drop sequence SEnmVlMngr;
drop table EnmVlMngr cascade constraints;
drop sequence SMBln;
drop table MBln cascade constraints;
drop sequence SFtchSclrCMD;
drop table FtchSclrCMD cascade constraints;
drop sequence SBscClcltn;
drop table BscClcltn cascade constraints;
drop sequence SNmInstnc;
drop table NmInstnc cascade constraints;
drop sequence SDltEnmCMD;
drop table DltEnmCMD cascade constraints;
drop sequence SFnctn;
drop table Fnctn cascade constraints;
drop sequence SAspctMngr;
drop table AspctMngr cascade constraints;
drop sequence SFtchRfrncCMD;
drop table FtchRfrncCMD cascade constraints;
drop sequence SRmvOprtnCMD;
drop table RmvOprtnCMD cascade constraints;
drop sequence SCrtCnstntCMD;
drop table CrtCnstntCMD cascade constraints;
drop sequence SAddRfrncCMD;
drop table AddRfrncCMD cascade constraints;
drop sequence SMAspct;
drop table MAspct cascade constraints;
drop sequence SCrtNmSchmCMD;
drop table CrtNmSchmCMD cascade constraints;
drop sequence SAccntMngr;
drop table AccntMngr cascade constraints;
drop sequence SAddEntrCMD;
drop table AddEntrCMD cascade constraints;
drop sequence SGtExstngCUCMD;
drop table GtExstngCUCMD cascade constraints;
drop sequence SCrtMssgCMD;
drop table CrtMssgCMD cascade constraints;
drop sequence SCrtAccntTpCMD;
drop table CrtAccntTpCMD cascade constraints;
drop sequence SObsrvtnMngr;
drop table ObsrvtnMngr cascade constraints;
drop sequence SMEnmVl;
drop table MEnmVl cascade constraints;
drop sequence SDvCMD;
drop table DvCMD cascade constraints;
drop sequence SAbsUntTp;
drop table AbsUntTp cascade constraints;
drop sequence SQnttMngr;
drop table QnttMngr cascade constraints;
drop sequence SNmSchmMngr;
drop table NmSchmMngr cascade constraints;
drop sequence SCrtSttcOpCMD;
drop table CrtSttcOpCMD cascade constraints;
drop sequence SAssctnMngr;
drop table AssctnMngr cascade constraints;
drop sequence SCrtAccntCMD;
drop table CrtAccntCMD cascade constraints;
drop sequence SCrtAtmcSbTpCMD;
drop table CrtAtmcSbTpCMD cascade constraints;
drop sequence SAbsQntt;
drop table AbsQntt cascade constraints;
drop sequence SCrtLnkCMD;
drop table CrtLnkCMD cascade constraints;
drop sequence SCrtVdOprtnCMD;
drop table CrtVdOprtnCMD cascade constraints;
drop sequence SCrtObsTpCMD;
drop table CrtObsTpCMD cascade constraints;
drop sequence SStDfltUntCMD;
drop table StDfltUntCMD cascade constraints;
drop sequence SChngAbstrctCMD;
drop table ChngAbstrctCMD cascade constraints;
drop sequence SCmmnDt;
drop table CmmnDt cascade constraints;
drop sequence SAvgStrtg;
drop table AvgStrtg cascade constraints;
drop sequence SDltObsTpCMD;
drop table DltObsTpCMD cascade constraints;
drop sequence SRmvAssctnCMD;
drop table RmvAssctnCMD cascade constraints;
drop sequence SHrrch;
drop table Hrrch cascade constraints;
drop sequence SAddFpCMD;
drop table AddFpCMD cascade constraints;
drop sequence SCrtSttcMssgCMD;
drop table CrtSttcMssgCMD cascade constraints;
drop sequence SCrtEnmVlCMD;
drop table CrtEnmVlCMD cascade constraints;
drop sequence STpMngr;
drop table TpMngr cascade constraints;
drop sequence SSbCMD;
drop table SbCMD cascade constraints;
drop sequence SMssgMngr;
drop table MssgMngr cascade constraints;
drop sequence SSmStrtg;
drop table SmStrtg cascade constraints;
drop sequence SMTp;
drop table MTp cascade constraints;
drop sequence SUntTpMngr;
drop table UntTpMngr cascade constraints;
drop sequence SCrtVdMssgCMD;
drop table CrtVdMssgCMD cascade constraints;
drop sequence SAbsUnt;
drop table AbsUnt cascade constraints;
drop sequence SEnmrtnMngr;
drop table EnmrtnMngr cascade constraints;
drop sequence SAddAssctnCMD;
drop table AddAssctnCMD cascade constraints;
drop sequence SRplcTpCMD;
drop table RplcTpCMD cascade constraints;
drop sequence SFtchSclrTpCMD;
drop table FtchSclrTpCMD cascade constraints;
drop sequence SCrtCnstCMD;
drop table CrtCnstCMD cascade constraints;
drop sequence SCrtOprtnCMD;
drop table CrtOprtnCMD cascade constraints;
drop sequence SChngUTNmCMD;
drop table ChngUTNmCMD cascade constraints;
drop sequence SFrctnMngr;
drop table FrctnMngr cascade constraints;
drop sequence SCnvrsn;
drop table Cnvrsn cascade constraints;
drop sequence SRfrnc;
drop table Rfrnc cascade constraints;
drop sequence SCrtObsrvtnCMD;
drop table CrtObsrvtnCMD cascade constraints;
drop sequence SDltAspctCMD;
drop table DltAspctCMD cascade constraints;
drop sequence SRfrncTp;
drop table RfrncTp cascade constraints;
drop sequence SObsTpMngr;
drop table ObsTpMngr cascade constraints;
drop sequence SMxStrtg;
drop table MxStrtg cascade constraints;
drop sequence SDltObsrvtnCMD;
drop table DltObsrvtnCMD cascade constraints;
drop sequence SMsrmntTpMng;
drop table MsrmntTpMng cascade constraints;
drop sequence SAddMltplFpCMD;
drop table AddMltplFpCMD cascade constraints;
drop sequence SLnkMngr;
drop table LnkMngr cascade constraints;
drop sequence SCrtAssctnCMD;
drop table CrtAssctnCMD cascade constraints;
drop sequence SMssgOrLnk;
drop table MssgOrLnk cascade constraints;
drop sequence SCrtAtmcRtTpCMD;
drop table CrtAtmcRtTpCMD cascade constraints;
drop sequence SAddCMD;
drop table AddCMD cascade constraints;
drop sequence SCnvrtCMD;
drop table CnvrtCMD cascade constraints;
drop sequence SCmmndExctr;
drop table CmmndExctr cascade constraints;
drop sequence SDltEnmVlCMD;
drop table DltEnmVlCMD cascade constraints;
drop sequence SAddRfrncTpCMD;
drop table AddRfrncTpCMD cascade constraints;
drop sequence SActlPrmtr;
drop table ActlPrmtr cascade constraints;
drop sequence SAddSbAccntCMD;
drop table AddSbAccntCMD cascade constraints;
drop sequence SNm;
drop table Nm cascade constraints;
drop sequence SAddFrctnCMD;
drop table AddFrctnCMD cascade constraints;
drop sequence SRmvFpFrmOpCMD;
drop table RmvFpFrmOpCMD cascade constraints;
drop sequence SFrctnWrppr;
drop table FrctnWrppr cascade constraints;
drop sequence SRmvMssgCMD;
drop table RmvMssgCMD cascade constraints;
drop sequence SFnctnMngr;
drop table FnctnMngr cascade constraints;
drop sequence SObjctMngr;
drop table ObjctMngr cascade constraints;
drop sequence SCrtFpCMD;
drop table CrtFpCMD cascade constraints;
drop sequence SCrtMObjctCMDOthrTps;
drop table CrtMObjctCMDOthrTps cascade constraints;
drop sequence SFtchCUCMDRfs;
drop table FtchCUCMDRfs cascade constraints;
drop sequence SCrTpDisjCMDAddnds;
drop table CrTpDisjCMDAddnds cascade constraints;
drop sequence SAbsOprtnPrmtrs;
drop table AbsOprtnPrmtrs cascade constraints;
drop sequence SCmpndQnttPrts;
drop table CmpndQnttPrts cascade constraints;
drop sequence SCrTpConjCMDFctrs;
drop table CrTpConjCMDFctrs cascade constraints;
drop sequence SCmpUntTpRfs;
drop table CmpUntTpRfs cascade constraints;
drop sequence SAssctnHrrchs;
drop table AssctnHrrchs cascade constraints;
drop sequence SOprtnMngrOprtns;
drop table OprtnMngrOprtns cascade constraints;
drop sequence SOprtnMngrFrmlPrmtrs;
drop table OprtnMngrFrmlPrmtrs cascade constraints;
drop sequence SMMxdCnjnctnFctrs;
drop table MMxdCnjnctnFctrs cascade constraints;
drop sequence SCmmndCrdntrExctr;
drop table CmmndCrdntrExctr cascade constraints;
drop sequence SAccntTpMngrAccntTps;
drop table AccntTpMngrAccntTps cascade constraints;
drop sequence SMObjctTps;
drop table MObjctTps cascade constraints;
drop sequence SGtExstngCUTCMDRfTps;
drop table GtExstngCUTCMDRfTps cascade constraints;
drop sequence SEnmVlMngrEnmVls;
drop table EnmVlMngrEnmVls cascade constraints;
drop sequence SMssgActlPrmtrs;
drop table MssgActlPrmtrs cascade constraints;
drop sequence SAspctMngrAspcts;
drop table AspctMngrAspcts cascade constraints;
drop sequence SAccntMngrAccnts;
drop table AccntMngrAccnts cascade constraints;
drop sequence SGtExstngCUCMDRfs;
drop table GtExstngCUCMDRfs cascade constraints;
drop sequence SCrtMssgCMDAp;
drop table CrtMssgCMDAp cascade constraints;
drop sequence SCmpUntRfs;
drop table CmpUntRfs cascade constraints;
drop sequence SObsrvtnMngrObsrvtns;
drop table ObsrvtnMngrObsrvtns cascade constraints;
drop sequence SQnttMngrQntts;
drop table QnttMngrQntts cascade constraints;
drop sequence SNmSchmMngrSchms;
drop table NmSchmMngrSchms cascade constraints;
drop sequence SNmSchmMngrNms;
drop table NmSchmMngrNms cascade constraints;
drop sequence SCrtSttcOpCMDFp;
drop table CrtSttcOpCMDFp cascade constraints;
drop sequence SAssctnMngrAssctns;
drop table AssctnMngrAssctns cascade constraints;
drop sequence SAssctnMngrHrrchs;
drop table AssctnMngrHrrchs cascade constraints;
drop sequence SCrtVdOprtnCMDFp;
drop table CrtVdOprtnCMDFp cascade constraints;
drop sequence SMAccntTpSbAccntTps;
drop table MAccntTpSbAccntTps cascade constraints;
drop sequence SCrtSttcMssgCMDAp;
drop table CrtSttcMssgCMDAp cascade constraints;
drop sequence SMxdTpDisjAddnds;
drop table MxdTpDisjAddnds cascade constraints;
drop sequence STpMngrTps;
drop table TpMngrTps cascade constraints;
drop sequence SNEATConjFctrs;
drop table NEATConjFctrs cascade constraints;
drop sequence SMssgMngrMssgs;
drop table MssgMngrMssgs cascade constraints;
drop sequence SUntTpMngrUntTps;
drop table UntTpMngrUntTps cascade constraints;
drop sequence SUntTpMngrRfTps;
drop table UntTpMngrRfTps cascade constraints;
drop sequence SUntTpMngrRfs;
drop table UntTpMngrRfs cascade constraints;
drop sequence SUntTpMngrUnts;
drop table UntTpMngrUnts cascade constraints;
drop sequence SCrtVdMssgCMDAp;
drop table CrtVdMssgCMDAp cascade constraints;
drop sequence SEnmrtnMngrEnmTps;
drop table EnmrtnMngrEnmTps cascade constraints;
drop sequence SNEDisjNFAddnds;
drop table NEDisjNFAddnds cascade constraints;
drop sequence SCrtOprtnCMDFp;
drop table CrtOprtnCMDFp cascade constraints;
drop sequence SFrctnMngrMngdFrctns;
drop table FrctnMngrMngdFrctns cascade constraints;
drop sequence SObsTpMngrObsrvtnTps;
drop table ObsTpMngrObsrvtnTps cascade constraints;
drop sequence SAccntSbAccnts;
drop table AccntSbAccnts cascade constraints;
drop sequence SAccntEntrs;
drop table AccntEntrs cascade constraints;
drop sequence SMsrmntTpMngMsrmntTps;
drop table MsrmntTpMngMsrmntTps cascade constraints;
drop sequence SAddMltplFpCMDFp;
drop table AddMltplFpCMDFp cascade constraints;
drop sequence SLnkMngrLnks;
drop table LnkMngrLnks cascade constraints;
drop sequence SCmmndExctrCommands;
drop table CmmndExctrCommands cascade constraints;
drop sequence SFnctnMngrFnctns;
drop table FnctnMngrFnctns cascade constraints;
drop sequence SObjctMngrObjcts;
drop table ObjctMngrObjcts cascade constraints;
