drop table Cls cascade constraints;
drop table DeletedObjects cascade constraints;
drop sequence SSpecialization;
drop table Specialization cascade constraints;
drop table Association cascade constraints;
drop table Association3 cascade constraints;
drop sequence STpMngr;
drop table TpMngr cascade constraints;
drop sequence SCmmndExctr;
drop table CmmndExctr cascade constraints;
drop sequence SAddAspctCMD;
drop table AddAspctCMD cascade constraints;
drop sequence SAspctMngr;
drop table AspctMngr cascade constraints;
drop sequence SSrvr;
drop table Srvr cascade constraints;
drop sequence SAddSbTpCMD;
drop table AddSbTpCMD cascade constraints;
drop sequence SMCmplxTp;
drop table MCmplxTp cascade constraints;
drop sequence SMAtmcTp;
drop table MAtmcTp cascade constraints;
drop sequence SCmmndCrdntr;
drop table CmmndCrdntr cascade constraints;
drop sequence SMAspct;
drop table MAspct cascade constraints;
drop sequence SCmmnDt;
drop table CmmnDt cascade constraints;
drop sequence SAddAtmcTpCMD;
drop table AddAtmcTpCMD cascade constraints;
drop sequence SCrtSbTpCMD;
drop table CrtSbTpCMD cascade constraints;
drop sequence STpMngrAtmcTps;
drop table TpMngrAtmcTps cascade constraints;
drop sequence STpMngrPrdctTps;
drop table TpMngrPrdctTps cascade constraints;
drop sequence STpMngrSmTps;
drop table TpMngrSmTps cascade constraints;
drop sequence SCmmndExctrCommands;
drop table CmmndExctrCommands cascade constraints;
drop sequence SAspctMngrAspcts;
drop table AspctMngrAspcts cascade constraints;
drop sequence SMCmplxTpCntndTps;
drop table MCmplxTpCntndTps cascade constraints;
drop sequence SCmmndCrdntrExctr;
drop table CmmndCrdntrExctr cascade constraints;
