drop table Cls cascade constraints;
drop table DeletedObjects cascade constraints;
drop sequence SSpecialization;
drop table Specialization cascade constraints;
drop table Association cascade constraints;
drop table Association3 cascade constraints;
drop sequence STpMngr;
drop table TpMngr cascade constraints;
drop sequence SCmmndExctr;
drop table CmmndExctr cascade constraints;
drop sequence SCrtHrrchCMD;
drop table CrtHrrchCMD cascade constraints;
drop sequence SAspctMngr;
drop table AspctMngr cascade constraints;
drop sequence SAddTHrrchCMD;
drop table AddTHrrchCMD cascade constraints;
drop sequence SAddSbTpCMD;
drop table AddSbTpCMD cascade constraints;
drop sequence SSrvr;
drop table Srvr cascade constraints;
drop sequence SAssctnMngr;
drop table AssctnMngr cascade constraints;
drop sequence SMCmplxTp;
drop table MCmplxTp cascade constraints;
drop sequence SMAtmcTp;
drop table MAtmcTp cascade constraints;
drop sequence SCrtAspctCMD;
drop table CrtAspctCMD cascade constraints;
drop sequence SCrtAtmcTpCMD;
drop table CrtAtmcTpCMD cascade constraints;
drop sequence SMAHrrch;
drop table MAHrrch cascade constraints;
drop sequence SCmmndCrdntr;
drop table CmmndCrdntr cascade constraints;
drop sequence SMAspct;
drop table MAspct cascade constraints;
drop sequence SCmmnDt;
drop table CmmnDt cascade constraints;
drop sequence SMAssctn;
drop table MAssctn cascade constraints;
drop sequence SCrtAssctnCMD;
drop table CrtAssctnCMD cascade constraints;
drop sequence SCrtSbTpCMD;
drop table CrtSbTpCMD cascade constraints;
drop sequence SMBln;
drop table MBln cascade constraints;
drop sequence STpMngrAtmcTps;
drop table TpMngrAtmcTps cascade constraints;
drop sequence STpMngrPrdctTps;
drop table TpMngrPrdctTps cascade constraints;
drop sequence STpMngrSmTps;
drop table TpMngrSmTps cascade constraints;
drop sequence SCmmndExctrCommands;
drop table CmmndExctrCommands cascade constraints;
drop sequence SAspctMngrAspcts;
drop table AspctMngrAspcts cascade constraints;
drop sequence SAssctnMngrAssctns;
drop table AssctnMngrAssctns cascade constraints;
drop sequence SAssctnMngrHrrchs;
drop table AssctnMngrHrrchs cascade constraints;
drop sequence SMCmplxTpCntndTps;
drop table MCmplxTpCntndTps cascade constraints;
drop sequence SCmmndCrdntrExctr;
drop table CmmndCrdntrExctr cascade constraints;
drop sequence SMAssctnHrrchs;
drop table MAssctnHrrchs cascade constraints;
