drop table Cls cascade constraints;
drop table DeletedObjects cascade constraints;
drop sequence SSpecialization;
drop table Specialization cascade constraints;
drop table Association cascade constraints;
drop table Association3 cascade constraints;
drop sequence SActrMngr;
drop table ActrMngr cascade constraints;
drop sequence SCmmndExctr;
drop table CmmndExctr cascade constraints;
drop sequence SCrtPrdctCMD;
drop table CrtPrdctCMD cascade constraints;
drop sequence SAddRlCMD;
drop table AddRlCMD cascade constraints;
drop sequence SPrdct;
drop table Prdct cascade constraints;
drop sequence SOrdr;
drop table Ordr cascade constraints;
drop sequence SCrtActrCMD;
drop table CrtActrCMD cascade constraints;
drop sequence SChngNmCMD;
drop table ChngNmCMD cascade constraints;
drop sequence SAddPstnCMD;
drop table AddPstnCMD cascade constraints;
drop sequence SSrvr;
drop table Srvr cascade constraints;
drop sequence SCmmndCrdntr;
drop table CmmndCrdntr cascade constraints;
drop sequence SActr;
drop table Actr cascade constraints;
drop sequence SCmmnDt;
drop table CmmnDt cascade constraints;
drop sequence SRl;
drop table Rl cascade constraints;
drop sequence SPstn;
drop table Pstn cascade constraints;
drop sequence SCrtOrdrCMD;
drop table CrtOrdrCMD cascade constraints;
drop sequence SActrMngrActrs;
drop table ActrMngrActrs cascade constraints;
drop sequence SCmmndExctrCommands;
drop table CmmndExctrCommands cascade constraints;
drop sequence SOrdrPstns;
drop table OrdrPstns cascade constraints;
drop sequence SCmmndCrdntrExctr;
drop table CmmndCrdntrExctr cascade constraints;
drop sequence SActrRls;
drop table ActrRls cascade constraints;
