
package model.visitor;

public interface CommandVisitor extends AspectManagerCommandVisitor,MessageManagerCommandVisitor,QuantityManagerCommandVisitor,AccountManagerCommandVisitor,UnitTypeManagerCommandVisitor,AssociationManagerCommandVisitor,TypeManagerCommandVisitor,AccountTypeManagerCommandVisitor,NameSchemeManagerCommandVisitor,MeasurementTypeManagerCommandVisitor,ObjectManagerCommandVisitor,LinkManagerCommandVisitor,NameSchemeInstaceManagerCommandVisitor,OperationManagerCommandVisitor,ConversionManagerCommandVisitor{
    
    
}
