
package model.visitor;

public interface CommandVisitor extends EnumerationManagerCommandVisitor,AspectManagerCommandVisitor,MessageManagerCommandVisitor,FractionManagerCommandVisitor,QuantityManagerCommandVisitor,AccountManagerCommandVisitor,UnitTypeManagerCommandVisitor,QuantifObjectCommandVisitor,AssociationManagerCommandVisitor,AccountTypeManagerCommandVisitor,TypeManagerCommandVisitor,EnumValueManagerCommandVisitor,MeasurementTypeManagerCommandVisitor,NameSchemeManagerCommandVisitor,MAccountTypeCommandVisitor,AccountCommandVisitor,ObservationManagerCommandVisitor,ObjectManagerCommandVisitor,LinkManagerCommandVisitor,OperationManagerCommandVisitor,ObsTypeManagerCommandVisitor{
    
    
}
