
package model.visitor;

public interface CommandVisitor extends AspectManagerCommandVisitor,MessageManagerCommandVisitor,FractionManagerCommandVisitor,QuantityManagerCommandVisitor,AccountManagerCommandVisitor,UnitTypeManagerCommandVisitor,QuantifObjectCommandVisitor,AssociationManagerCommandVisitor,AccountTypeManagerCommandVisitor,TypeManagerCommandVisitor,NameSchemeManagerCommandVisitor,MAccountTypeCommandVisitor,MeasurementTypeManagerCommandVisitor,AccountCommandVisitor,ObjectManagerCommandVisitor,LinkManagerCommandVisitor,OperationManagerCommandVisitor{
    
    
}
