
package model.visitor;
import model.UserException;
public interface CommandExceptionVisitor<E extends UserException> extends AspectManagerCommandExceptionVisitor<E>,MessageManagerCommandExceptionVisitor<E>,QuantityManagerCommandExceptionVisitor<E>,AccountManagerCommandExceptionVisitor<E>,UnitTypeManagerCommandExceptionVisitor<E>,AssociationManagerCommandExceptionVisitor<E>,TypeManagerCommandExceptionVisitor<E>,AccountTypeManagerCommandExceptionVisitor<E>,NameSchemeManagerCommandExceptionVisitor<E>,MeasurementTypeManagerCommandExceptionVisitor<E>,ObjectManagerCommandExceptionVisitor<E>,LinkManagerCommandExceptionVisitor<E>,NameSchemeInstaceManagerCommandExceptionVisitor<E>,OperationManagerCommandExceptionVisitor<E>,ConversionManagerCommandExceptionVisitor<E>{
    
    
}
