package constants;

public class IconConstants {

	// tree icons
	public static final String ICON_BULLET_BALL_GLASS_BLUE = "bullet_ball_glass_blue.png";
	public static final String ICON_BULLET_BALL_GLASS_GREEN = "bullet_ball_glass_green.png";
	public static final String ICON_BULLET_BALL_GLASS_GREY = "bullet_ball_glass_grey.png";
	public static final String ICON_BULLET_BALL_GLASS_RED = "bullet_ball_glass_red.png";
	public static final String ICON_BULLET_BALL_GLASS_YELLOW = "bullet_ball_glass_yellow.png";
	public static final String ICON_BULLET_BALL_RED = "bullet_ball_red.png";
	public static final String ICON_CUBE_BLUE = "cube_blue.png";
	public static final String ICON_CUBE_MOLECULE = "cube_molecule.png";
	public static final String ICON_CUBES_BLUE = "cubes_blue.png";
	public static final String ICON_BOOKS = "books.png";
	public static final String ICON_BUG_RED = "bug_red.png";
	public static final String ICON_NAV_REFRESH_BLUE = "nav_refresh_blue.png";
	public static final String ICON_SCALES = "scales.png";
	public static final String ICON_SHELF = "shelf.png";
	public static final String ICON_SHOPPINGBASKET_FULL = "shoppingbasket_full.png";
	public static final String ICON_SHOPPINGCART_FULL = "shoppingcart_full.png";
	public static final String ICON_TRANSFORM = "transform.png";
	public static final String ICON_PIE_CHART = "pie-chart.png";
	public static final String ICON_CUBES = "cubes.png";
	public static final String ICON_INDEX = "index.png";
	public static final String ICON_GRAPH_EDGE_DIRECTED = "graph_edge_directed.png";
	public static final String ICON_COOKIES = "cookies.png";
	public static final String ICON_DOWN_MINUS = "down_minus.png";
	public static final String ICON_UP_PLUS = "up_plus.png";
	public static final String ICON_FIND_TEXT = "find_text.png";
	public static final String ICON_ELEMENT_FIND = "element_find.png";
	public static final String ICON_PLANET = "planet.png";
	public static final String ICON_PERCENT = "percent.png";
	public static final String ICON_PACKAGE = "package.png";
	public static final String ICON_BOOK_OPEN2 = "book_open2.png";
	public static final String ICON_FOLDER2_GREEN = "folder2_green.png";
	public static final String ICON_FORM_GREEN = "form_green.png";
	public static final String ICON_TAPE_MEASURE2 = "tape_measure2.png";
	public static final String ICON_WAR = "war.png";
	public static final String ICON_THERMOMETER = "thermometer.png";
	public static final String ICON_THERMOMETER2 = "thermometer2.png";
	public static final String ICON_GRAPH_NODE = "graph_node.png";
	public static final String ICON_STAR_BLUE = "star_blue.png";
	public static final String ICON_DICTIONARY = "dictionary.png";
	public static final String ICON_DOCUMENT_CERTIFICATE = "document_certificate.png";
	public static final String ICON_MAIL_SERVER = "mail_server.png";
	public static final String ICON_MAIL = "mail.png";
	public static final String ICON_TEACHER = "teacher.png";
	public static final String ICON_BLACKBOARD = "blackboard.png";
	public static final String ICON_TICKET_GREEN = "ticket_green.png";
	public static final String ICON_TICKET_RED = "ticket_red.png";
	public static final String ICON_DIE = "die.png";
	public static final String ICON_LINK = "link.png";
	public static final String ICON_KEYS = "keys.png";
	public static final String ICON_CRUTCH = "crutch.png";
	public static final String ICON_GRAPHICS_TABLET = "graphics-tablet.png";
	public static final String ICON_DOCUMENTS_GEAR = "documents_gear.png";
	public static final String ICON_GEAR = "gear.png";
	public static final String ICON_GEARS = "gears.png";
	public static final String ICON_SELECTION = "selection.png";
	public static final String ICON_ENVIRONMENT_VIEW = "environment_view.png";
	public static final String ICON_SPY = "spy.png";
	public static final String ICON_COFFEEBEAN = "coffeebean.png";
	public static final String ICON_JAR_BEAN = "jar_bean.png";
	public static final String ICON_BULLET_BALL_GREY = "bullet_ball_grey.png";
	public static final String ICON_LOGIC_AND = "logic_and.png";
	public static final String ICON_LOGIC_OR = "logic_or.png";
	public static final String ICON_TEXT_TREE = "text_tree.png";
	public static final String ICON_TABLE = "table.png";
	public static final String ICON_TABLE_VIEW = "table_view.png";
	public static final String ICON_TABLE_SQL = "table_sql.png";
	public static final String ICON_TABLE_SQL_VIEW = "table_sql_view.png";

	public static final String ICON_LARGE_CUBES = "large/cubes.png";
	public static final String ICON_LARGE_PIE_CHART = "large/pie-chart.png";
	public static final String ICON_LARGE_INDEX = "large/index.png";
	public static final String ICON_LARGE_GRAPH_EDGE_DIRECTED = "large/graph_edge_directed.png";
	public static final String ICON_LARGE_COOKIES = "large/cookies.png";

}
