drop table Cls cascade constraints;
drop table DeletedObjects cascade constraints;
drop sequence SSpecialization;
drop table Specialization cascade constraints;
drop table Association cascade constraints;
drop table Association3 cascade constraints;
drop sequence SMAtmcTp;
drop table MAtmcTp cascade constraints;
drop sequence SSrvr;
drop table Srvr cascade constraints;
drop sequence SMCmplxTp;
drop table MCmplxTp cascade constraints;
drop sequence SMCmplxTpCntndTps;
drop table MCmplxTpCntndTps cascade constraints;
