drop table Cls cascade constraints;
drop table DeletedObjects cascade constraints;
drop sequence SSpecialization;
drop table Specialization cascade constraints;
drop table Association cascade constraints;
drop table Association3 cascade constraints;
drop sequence SCrtAktrCMD;
drop table CrtAktrCMD cascade constraints;
drop sequence SCmmndExctr;
drop table CmmndExctr cascade constraints;
drop sequence SAddRlCMD;
drop table AddRlCMD cascade constraints;
drop sequence SCmmndCrdntr;
drop table CmmndCrdntr cascade constraints;
drop sequence SAktr;
drop table Aktr cascade constraints;
drop sequence SCmmnDt;
drop table CmmnDt cascade constraints;
drop sequence SRll;
drop table Rll cascade constraints;
drop sequence SAktrMngr;
drop table AktrMngr cascade constraints;
drop sequence SSrvr;
drop table Srvr cascade constraints;
drop sequence SCmmndExctrCommands;
drop table CmmndExctrCommands cascade constraints;
drop sequence SCmmndCrdntrExctr;
drop table CmmndCrdntrExctr cascade constraints;
drop sequence SAktrMngrAktr;
drop table AktrMngrAktr cascade constraints;
